QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Models/ChuyenKhoa.cs
using System;
using System.Collections.Generic;

namespace QuanLyHocSinh_ASP_MVC_Demo.Models
{
    public partial class ChuyenKhoa
    {
        public ChuyenKhoa()
        {
            HocSinhs = new HashSet<HocSinh>();
        }

        public string MaKhoa { get; set; } = null!;
        public string TenKhoa { get; set; } = null!;
        public string? SoDienThoai { get; set; }
        public bool? Spam { get; set; }

        public virtual ICollection<HocSinh> HocSinhs { get; set; }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Controllers/ChuyenKhoaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using QuanLyHocSinh_ASP_MVC_Demo.Models;

namespace QuanLyHocSinh_ASP_MVC_Demo.Controllers
{
    public class ChuyenKhoaController : Controller
    {
        public IActionResult Index(int message = 2)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var lstChuyenKhoa = context.ChuyenKhoas.ToList();
                ViewBag.message = message;

                return View("Index",lstChuyenKhoa);
            }

        }
        public IActionResult AddChuyenKhoa(int message = 4)
        {
            ViewBag.message = message;
            return View();
        }
        [HttpPost]
        public IActionResult AddChuyenKhoa(ChuyenKhoa chuyenKhoa)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                context.ChuyenKhoas.Add(chuyenKhoa);
                if (context.SaveChanges() > 0)
                {
                    return RedirectToAction("Index",new { message = 3});
                }
                else
                {
                    return RedirectToAction("AddChuyenKhoa",new { message = 0});
                }
            }
        }

        public IActionResult DetailChuyenKhoa(string maChuyenKhoa)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var chuyenKhoa = context.ChuyenKhoas.FirstOrDefault(x => x.MaKhoa.Equals(maChuyenKhoa));
                    return View(chuyenKhoa);
            }

        }
        public IActionResult UpdateChuyenKhoa(string maChuyenKhoa)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var chuyenKhoa = context.ChuyenKhoas.FirstOrDefault(x => x.MaKhoa.Equals(maChuyenKhoa));
                return View(chuyenKhoa);
            }

        }

        [HttpPost]
        public IActionResult UpdateChuyenKhoa(ChuyenKhoa chuyenKhoa)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                context.ChuyenKhoas.Update(chuyenKhoa);
                if (context.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("UpdateChuyenKhoa");
                }

            }
        }

        public IActionResult DeleteChuyenKhoa(string maChuyenKhoa)
        {
            using(QuanLyHocSinhContext context =new QuanLyHocSinhContext())
            {
                var chuyenKhoa = context.ChuyenKhoas.Include(h => h.HocSinhs).FirstOrDefault(c => c.MaKhoa.Equals(maChuyenKhoa));
                
                try
                {
                    if(chuyenKhoa != null)
                    {
                        if(chuyenKhoa.HocSinhs.Count() > 0)
                        {
                            foreach (HocSinh item in chuyenKhoa.HocSinhs)
                            {
                                List<DiemThi> listDiemThi = 
                                    context.DiemThis
                                    .Where(x => x.MaSv.Equals(item.MaSv)).ToList();
                                if(listDiemThi.Count() > 0)
                                {
                                    context.DiemThis.RemoveRange(listDiemThi);
                                    context.SaveChanges();
                                }
                            }
                            context.HocSinhs.RemoveRange(chuyenKhoa.HocSinhs);
                            context.SaveChanges();  
                        }
                        context.ChuyenKhoas.Remove(chuyenKhoa);
                        context.SaveChanges();
                        return RedirectToAction("Index", new {message = 1});
                    }
                }catch(Exception ex)
                {
                    
                }
                return RedirectToAction("Index", new { message = 0 });
            }
        }

        public IActionResult SpamChuyenKhoa(string maChuyenKhoa)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var chuyenKhoa = context.ChuyenKhoas.FirstOrDefault(x => x.MaKhoa.Equals(maChuyenKhoa));
                if(chuyenKhoa != null)
                {
                    chuyenKhoa.Spam = !chuyenKhoa.Spam;
                    context.ChuyenKhoas.Update(chuyenKhoa);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }

    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/ChuyenKhoa/AddChuyenKhoa.cshtml
@model QuanLyHocSinh_ASP_MVC_Demo.Models.ChuyenKhoa
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "AddChuyenKhoa";
}

<h1>AddChuyenKhoa</h1>

<h4>ChuyenKhoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddChuyenKhoa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaKhoa" class="control-label"></label>
                <input asp-for="MaKhoa" class="form-control" />
                <span asp-validation-for="MaKhoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenKhoa" class="control-label"></label>
                <input asp-for="TenKhoa" class="form-control" />
                <span asp-validation-for="TenKhoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spam" class="control-label"></label>
                <br />
                On: <input type="radio" asp-for="Spam" class="form-control" value="true" checked/>
                OFF:<input type="radio" asp-for="Spam" class="form-control" value="false"/>
                <span asp-validation-for="Spam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/ChuyenKhoa/DetailChuyenKhoa.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using QuanLyHocSinh_ASP_MVC_Demo.Models
@model ChuyenKhoa

 MaKhoa:@Model.MaKhoa
<br />
TenKhoa:@Model.TenKhoa
<br />
SoDienThoai:@Model.SoDienThoai

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/ChuyenKhoa/Index.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<QuanLyHocSinh_ASP_MVC_Demo.Models.ChuyenKhoa>

@{
    ViewData["Title"] = "Index";
}


<h1>Index</h1>

<p>
    <a asp-controller="ChuyenKhoa" asp-action="AddChuyenKhoa">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaKhoa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenKhoa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaKhoa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenKhoa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoDienThoai)
                </td>
                <td>
                    @if (item.Spam == true)
                    {
                        <a asp-controller="ChuyenKhoa" asp-action="UpdateChuyenKhoa" asp-route-maChuyenKhoa="@item.MaKhoa">Edit</a> 
                        <a asp-controller="ChuyenKhoa" asp-action="DetailChuyenKhoa" asp-route-maChuyenKhoa="@item.MaKhoa">Details</a> 
                         <a asp-controller="ChuyenKhoa" asp-action="DeleteChuyenKhoa" asp-route-maChuyenKhoa="@item.MaKhoa">Delete</a> 
                    }

                    <a asp-controller="ChuyenKhoa" asp-action="SpamChuyenKhoa" asp-route-maChuyenKhoa="@item.MaKhoa"> Spam </a>
                   
                </td>
            </tr>
        }
        @if (ViewBag.message != null)
        {
            
            @if (ViewBag.message == 1)
            {
                <script>alert("Delete thanh cong");</script>
            }else if(ViewBag.message == 3)
            {
                <script>alert("Add thanh cong");</script>
            }
            else if (@ViewBag.message == 0)
            {
                <script>alert("Delete ko thanh cong");</script>
            }
        }

        

    </tbody>
</table>

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/ChuyenKhoa/UpdateChuyenKhoa.cshtml
@model QuanLyHocSinh_ASP_MVC_Demo.Models.ChuyenKhoa
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "UpdateChuyenKhoa";
}

<h1>UpdateChuyenKhoa</h1>

<h4>ChuyenKhoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateChuyenKhoa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaKhoa" />
            <div class="form-group">
                <label asp-for="TenKhoa" class="control-label"></label>
                <input asp-for="TenKhoa" class="form-control" />
                <span asp-validation-for="TenKhoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}