QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Models/HocSinh.cs
using System;
using System.Collections.Generic;

namespace QuanLyHocSinh_ASP_MVC_Demo.Models
{
    public partial class HocSinh
    {
        public HocSinh()
        {
            DiemThis = new HashSet<DiemThi>();
        }

        public string MaSv { get; set; } = null!;
        public string HoTen { get; set; } = null!;
        public bool? GioiTinh { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string? DienThoai { get; set; }
        public string? Email { get; set; }
        public string? DiaChi { get; set; }
        public string? MaKhoa { get; set; }
        public string? Passworld { get; set; }
        public bool? Spam { get; set; }

        public virtual ChuyenKhoa? MaKhoaNavigation { get; set; }
        public virtual ICollection<DiemThi> DiemThis { get; set; }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Controllers/HocSinhController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyHocSinh_ASP_MVC_Demo.Models;

namespace QuanLyHocSinh_ASP_MVC_Demo.Controllers
{
    public class HocSinhController : Controller
    {

        public IActionResult Index()
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var listHocSinh = context.HocSinhs.Include(x => x.MaKhoaNavigation).ToList();
                //var data1 = context.ChuyenKhoas.ToList();
                //ViewBag.ChuyenKhoas = data1;
                return View(listHocSinh);
            }
        }

        public IActionResult AddHocSinh(int mess = 1)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var data = context.ChuyenKhoas.Where(x=>x.Spam == true).ToList();
                ViewBag.ChuyenKhoas = data;

                ViewBag.Mess = mess;
                return View();
            }
        }

        [HttpPost]
        public IActionResult AddHocSinh(HocSinh hocSinh)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {

                
                try
                {
                    ChuyenKhoa chuyenKhoa = context.ChuyenKhoas.FirstOrDefault(x=> x.MaKhoa == hocSinh.MaKhoa && x.Spam == true);
                    if(chuyenKhoa != null)
                    {
                        context.HocSinhs.Add(hocSinh);
                        if (context.SaveChanges() > 0)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                        
                }catch(Exception ex)
                {
                    
                }
               
                return RedirectToAction("AddHocSinh");

            }
        }

        public IActionResult UpdateHocSinh(string id)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var listChuyenKhoa = context.ChuyenKhoas.Where(x=>x.Spam == true).ToList();
                ViewBag.ChuyenKhoas = listChuyenKhoa;

                var hocSinh = context.HocSinhs.FirstOrDefault(x=>x.MaSv.Equals(id));
                return View(hocSinh);
            }
        }

        [HttpPost]
        public IActionResult UpdateHocSinh(HocSinh hocSinh)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                context.HocSinhs.Update(hocSinh);
                if (context.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("UpdateHocSinh");
                }
               
            }
        }

        public IActionResult DeleteHocSinh(string id)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var hocSinh = context.HocSinhs.Include(x=>x.DiemThis).FirstOrDefault(x => x.MaSv.Equals(id));
                if(hocSinh != null)
                {
                    foreach (DiemThi item in hocSinh.DiemThis)
                    {
                        List<DiemThi> listDiemThi = context.DiemThis.Where(x => x.MaSv.Equals(item.MaSv)).ToList();
                        if(listDiemThi.Count() > 0)
                        {
                            context.DiemThis.RemoveRange(listDiemThi);
                            context.SaveChanges();
                        }
                    }
                }
                context.HocSinhs.Remove(hocSinh);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public IActionResult DetailHocSinh(string id)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var hocSinh = context.HocSinhs.Include(x=>x.MaKhoaNavigation).FirstOrDefault(x=>x.MaSv.Equals(id));
                return View(hocSinh);
            }
        }

        public void ShowMessage(string message)
        {
            TempData["Message"] = message;
        }
        public IActionResult SpamHocSinh(string id)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var hocSinh = context.HocSinhs.FirstOrDefault(x => x.MaSv.Equals(id));
                if (hocSinh != null)
                {
                    hocSinh.Spam = ! hocSinh.Spam;
                    if(hocSinh.Spam == true)
                    {
                        ShowMessage("Active Ok");
                    }
                    if(hocSinh.Spam == false)
                    {
                        ShowMessage("Locked Hoc Sinh Ok");
                    }
                    context.HocSinhs.Update(hocSinh);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Pages/HocSinhs/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuanLyHocSinh_ASP_MVC_Demo.Pages.HocSinhs
{
    public class IndexModel : PageModel
    {
        public string Thanh { get; set; }

        public void OnGet()
        {
            Thanh = "10 diem";
        }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Pages/HocSinhs/thanh.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuanLyHocSinh_ASP_MVC_Demo.Pages.HocSinhs
{
    public class thanhModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/HocSinh/AddHocSinh.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using QuanLyHocSinh_ASP_MVC_Demo.Models
@model HocSinh

<form asp-action="AddHocSinh" asp-controller="HocSinh" method="post">
    MaHocSinh:<input type="text" asp-for="MaSv" />
    <br />
    HoTen:<input type="text" asp-for="HoTen" />
    <br />
    GioiTinh:
    <br />
    Male:<input type="radio" asp-for="GioiTinh" value="true" checked="true"/>
    FeMale:<input type="radio" asp-for="GioiTinh" value="false"/>
    <br />
    NgaySinh:<input type="date" asp-for="NgaySinh" />
    <br />
    DienThoai:<input type="text" asp-for="DienThoai" />
    <br />
    Email:<input type="email" asp-for="Email" />
    <br />
    DiaChi:<input type="text" asp-for="DiaChi" />
    <br />
    ChuyenKhoa:
    <select asp-for="MaKhoa">
        @foreach (ChuyenKhoa c in @ViewBag.ChuyenKhoas)
        {
            <option value="@c.MaKhoa">@c.TenKhoa</option>
        }
    </select>
    <input type="submit" value="Add" />

</form>

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/HocSinh/DetailHocSinh.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using QuanLyHocSinh_ASP_MVC_Demo.Models
@model HocSinh

MaSV:@Model.MaSv
<br />HoTen:@Model.HoTen
<br />GioiTinh:@Model.GioiTinh
<br />NgaySinh:@Model.NgaySinh
<br />DienThoai:@Model.DienThoai
<br />Email:@Model.Email
<br />DiaChi:@Model.DiaChi
<br />ChuyenKhoa:@Model.MaKhoaNavigation.TenKhoa

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/HocSinh/Index.cshtml
@model IEnumerable<QuanLyHocSinh_ASP_MVC_Demo.Models.HocSinh>
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="AddHocSinh" asp-controller="HocSinh" method="get">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                ChuyenKhoa
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.HoTen)
                </td>
                <td>
                    @(item.GioiTinh == true ? "Nam" : "Nu")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DienThoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaKhoaNavigation.TenKhoa)
                </td>
                <td>
                    @if (item.Spam == true)
                    {
                        <a asp-controller="HocSinh" asp-action="UpdateHocSinh" asp-route-id="@item.MaSv">Edit</a>
                        <a asp-controller="HocSinh" asp-action="DetailHocSinh" asp-route-id="@item.MaSv">Details</a>
                        <a asp-controller="HocSinh" asp-action="DeleteHocSinh" asp-route-id="@item.MaSv">Delete</a>
                    }

                    <a asp-controller="HocSinh" asp-action="SpamHocSinh" asp-route-id="@item.MaSv">Spam</a>
                </td>
            </tr>
        }
        @if (TempData["Message"] != null)
        {
            <script>
                alert('@TempData["Message"]');
            </script>
        }
    </tbody>
</table>

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/HocSinh/UpdateHocSinh.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using QuanLyHocSinh_ASP_MVC_Demo.Models
@model HocSinh

<form asp-action="UpdateHocSinh" asp-controller="HocSinh" method="post">
    MaHocSinh:<input type="text" asp-for="MaSv" readonly="true"/>
    <br />
    HoTen:<input type="text" asp-for="HoTen" />
    <br />
    GioiTinh:
    <br />
    Male:<input type="radio" asp-for="GioiTinh" value="true" checked="true" />
    FeMale:<input type="radio" asp-for="GioiTinh" value="false" />
    <br />
    NgaySinh:<input type="date" asp-for="NgaySinh" />
    <br />
    DienThoai:<input type="text" asp-for="DienThoai" />
    <br />
    Email:<input type="email" asp-for="Email" />
    <br />
    DiaChi:<input type="text" asp-for="DiaChi" />
    <br />
    ChuyenKhoa:
    <select asp-for="MaKhoa">
        @foreach (ChuyenKhoa c in @ViewBag.ChuyenKhoas)
        {
            <option value="@c.MaKhoa">@c.TenKhoa</option>
        }
    </select>
    <input type="submit" value="Add" />

</form>