QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Models/MonHoc.cs
using System;
using System.Collections.Generic;

namespace QuanLyHocSinh_ASP_MVC_Demo.Models
{
    public partial class MonHoc
    {
        public MonHoc()
        {
            DiemThis = new HashSet<DiemThi>();
        }

        public int MaMh { get; set; }
        public string TenMonHoc { get; set; } = null!;
        public double? SoTinChi { get; set; }
        public string? Status { get; set; }
        public bool? Spam { get; set; }

        public virtual ICollection<DiemThi> DiemThis { get; set; }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Controllers/MonHocController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyHocSinh_ASP_MVC_Demo.Models;

namespace QuanLyHocSinh_ASP_MVC_Demo.Controllers
{
    public class MonHocController : Controller
    {
        public IActionResult Index()
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var listMonHoc = context.MonHocs.ToList();
                return View(listMonHoc);
            }

        }

        public IActionResult AddMonHoc()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddMonHoc(MonHoc monHoc)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                context.MonHocs.Add(monHoc);
                if (context.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("AddMonHoc");
                }
            }
        }

        public IActionResult UpdateMonHoc(int maMonHoc)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var monHoc = context.MonHocs.FirstOrDefault(x => x.MaMh == maMonHoc);
                return View(monHoc);
            }

        }

        [HttpPost]
        public IActionResult UpdateMonHoc(MonHoc monHoc)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            { 
                context.MonHocs.Update(monHoc);
                if (context.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("UpdateMonHoc");
                }
            }
        }

        public IActionResult DetailMonHoc(int maMonHoc)
        {
            using (QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var monHoc = context.MonHocs.FirstOrDefault(x => x.MaMh == maMonHoc);
                return View(monHoc);
            }

        }
        public IActionResult DeleteMonHoc(int maMonHoc)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                MonHoc monHoc = context.MonHocs.Include(x=>x.DiemThis).FirstOrDefault(x=>x.MaMh== maMonHoc);
                try
                {
                    if(monHoc != null)
                    {
                        if (monHoc.DiemThis.Count() > 0)
                        {
                            foreach(DiemThi item in monHoc.DiemThis)
                            {
                                List<DiemThi> listDiemThi = context.DiemThis.Where(x=>x.MaMh == item.MaMh).ToList();
                                if (listDiemThi.Count() > 0)
                                {
                                    context.DiemThis.RemoveRange(listDiemThi);
                                    context.SaveChanges();

                                }
                            }
                        }
                        context.MonHocs.Remove(monHoc);
                        context.SaveChanges();
                    }
                }catch(Exception ex)
                {
                    throw new Exception(ex.Message);
                }
                return RedirectToAction("Index");    
            }
        }

        public IActionResult SapmMonHoc(int maMonHoc)
        {
            using(QuanLyHocSinhContext context = new QuanLyHocSinhContext())
            {
                var monHoc = context.MonHocs.FirstOrDefault(x => x.MaMh == maMonHoc);
                if(monHoc != null)
                {
                    monHoc.Spam = !monHoc.Spam;
                    context.MonHocs.Update(monHoc);
                    context.SaveChanges(true);
                }
                return RedirectToAction("Index");
            }
        }
    }
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/MonHoc/AddMonHoc.cshtml
@model QuanLyHocSinh_ASP_MVC_Demo.Models.MonHoc
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "AddMonHoc";
}

<h1>AddMonHoc</h1>

<h4>MonHoc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddMonHoc" asp-controller="MonHoc">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenMonHoc" class="control-label"></label>
                <input asp-for="TenMonHoc" class="form-control" />
                <span asp-validation-for="TenMonHoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoTinChi" class="control-label"></label>
                <input asp-for="SoTinChi" class="form-control" />
                <span asp-validation-for="SoTinChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spam" class="control-label"></label>
                <br />
                Activate: <input asp-for="Spam" type="radio" value="true" class="form-control" />
                Ban: <input asp-for="Spam" value="fales" type="radio" class="form-control" />
                <span asp-validation-for="Spam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/MonHoc/DetailMonHoc.cshtml
@model QuanLyHocSinh_ASP_MVC_Demo.Models.MonHoc
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "DetailMonHoc";
}

<h1>DetailMonHoc</h1>

<div>
    <h4>MonHoc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenMonHoc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenMonHoc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoTinChi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoTinChi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spam)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaMh">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/MonHoc/Index.cshtml
@model IEnumerable<QuanLyHocSinh_ASP_MVC_Demo.Models.MonHoc>
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="MonHoc" asp-action="AddMonHoc">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenMonHoc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoTinChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenMonHoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoTinChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                    @if(item.Spam == true)
                    {
                        <a asp-controller="MonHoc" asp-action="UpdateMonHoc" asp-route-maMonHoc="@item.MaMh">Edit</a>
                        <a asp-controller="MonHoc" asp-action="DetailMonHoc" asp-route-maMonHoc="@item.MaMh">Details</a>
                        <a asp-controller="MonHoc" asp-action="DeleteMonHoc" asp-route-maMonHoc="@item.MaMh">Delete</a>
                    }

                    <a asp-controller="MonHoc" asp-action="SapmMonHoc" asp-route-maMonHoc="@item.MaMh">Spam</a>

            </td>
        </tr>
}
    </tbody>
</table>

QuanLyHocSinh_ASP_MVC_Demo/QuanLyHocSinh_ASP_MVC_Demo/Views/MonHoc/UpdateMonHoc.cshtml
@model QuanLyHocSinh_ASP_MVC_Demo.Models.MonHoc
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "UpdateMonHoc";
}

<h1>UpdateMonHoc</h1>

<h4>MonHoc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateMonHoc">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaMh" />
            <div class="form-group">
                <label asp-for="TenMonHoc" class="control-label"></label>
                <input asp-for="TenMonHoc" class="form-control" />
                <span asp-validation-for="TenMonHoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoTinChi" class="control-label"></label>
                <input asp-for="SoTinChi" class="form-control" />
                <span asp-validation-for="SoTinChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spam" class="control-label"></label>
                <input asp-for="Spam" class="form-control" />
                <span asp-validation-for="Spam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}